package org.emergent.semversa

/** Version information generated by the plug-in. */
class VersionInfo(
    var scmExists: Boolean = true,
    var scm: String = "n/a",
    var branch: String = "",
    var branchType: String = "",
    var branchId: String = "",
    var commit: String = "",
    var display: String = "",
    var full: String = "",
    var base: String = "",
    var build: String = "",
    var time: String? = null,
    var tag: String? = null,
    var lastTag: String? = null,
    var dirty: Boolean = false,
    var shallow: Boolean = false,
    var versionNumber: VersionNumber? = null,
) {
    constructor(version: String, resolved: Resolved) : this(
        full = version,
        branch = resolved.branch,
        commit = resolved.hash,
        branchType = if (resolved.detached) "detached" else "branch",
        dirty = resolved.dirty
    )


    companion object {
        @JvmField val NONE = VersionInfo(scmExists = false, full = "unspecified")
    }
}
